// Box data
export const FETCH_BOX_REQUEST = 'FETCH_BOX_REQUEST'
export const FETCH_BOX_SUCCESS = 'FETCH_BOX_SUCCESS'
export const FETCH_BOX_FAILURE = 'FETCH_BOX_FAILURE'

// Shipping form
export const SET_CITY = 'ORDER/SET_CITY'
export const SET_STREET_ADDRESS = 'ORDER/SET_STREET_ADDRESS'
export const SET_FULL_ADDRESS = 'ORDER/SET_FULL_ADDRESS'
export const SUBMIT_SHIPPING_FORM = 'ORDER/SUBMIT_SHIPPING_FORM'

// Cities
export const FETCH_CITIES_REQUEST = 'ORDER/FETCH_CITIES_REQUEST'
export const FETCH_CITIES_SUCCESS = 'ORDER/FETCH_CITIES_SUCCESS'
export const FETCH_CITIES_FAILURE = 'ORDER/FETCH_CITIES_FAILURE'
